// apps/web/src/app/page.tsx
'use client'; // This component is interactive, so mark it as a client component

import React, { useState, useEffect, useCallback } from 'react';

// Define the structure for paper data (matching the API response)
interface Paper {
  id: string; // arXiv ID (e.g., '2310.12345')
  title: string;
  summary: string; // Original abstract from arXiv
  authors: string[];
  published: string;
  updated: string;
  pdfLink: string;
  categories: string[]; // Replaces the previous 'tags'
  aiSummary?: string; // Optional: Summary generated by Gemini
}

export default function HomePage() {
  // State to hold the list of papers fetched from the API
  const [papers, setPapers] = useState<Paper[]>([]);
  // State to track the index of the currently displayed paper
  const [currentPaperIndex, setCurrentPaperIndex] = useState(0);
  // State to store the IDs of liked papers
  const [likedPapers, setLikedPapers] = useState<string[]>([]); // This variable is now used
  // State to display messages (loading, errors, end of list)
  const [message, setMessage] = useState<string | null>('論文を読み込み中...'); // Initial loading message
  // State to manage the loading status
  const [isLoading, setIsLoading] = useState(true);
  // State to track if AI summary generation is in progress
  const [isSummarizing, setIsSummarizing] = useState(false);

  // Function to fetch paper data from the /api/papers endpoint
  const fetchPapers = useCallback(async () => {
    setIsLoading(true); // Set loading state to true
    setMessage('論文を読み込み中...'); // Update loading message
    try {
      const response = await fetch('/api/papers'); // Call the API route
      if (!response.ok) {
        // Handle HTTP errors
        const errorData = await response.json().catch(() => ({})); // Try to parse error details
        throw new Error(`論文データの取得に失敗しました。 Status: ${response.status}. ${errorData.error || ''}`);
      }
      const data: Paper[] = await response.json(); // Parse the JSON response

      if (data && data.length > 0) {
        setPapers(data); // Update the papers state
        setCurrentPaperIndex(0); // Reset index to show the first paper
        setMessage(null); // Clear any previous messages
      } else {
        // Handle case where no papers are returned
        setPapers([]);
        setMessage('表示できる論文が見つかりませんでした。');
      }
    } catch (error) {
      console.error('Failed to fetch papers:', error);
      // Set error message for the user
      setMessage(`論文の読み込み中にエラーが発生しました: ${error instanceof Error ? error.message : '不明なエラー'}`);
      setPapers([]); // Clear papers on error
    } finally {
      setIsLoading(false); // Set loading state to false regardless of success or failure
    }
  }, []); // Empty dependency array means this function is created once

  // Fetch papers when the component mounts
  useEffect(() => {
    fetchPapers();
  }, [fetchPapers]); // Dependency array includes fetchPapers

  // Get the currently displayed paper object based on the index
  const currentPaper = papers[currentPaperIndex];

  // Function to generate AI summary using the /api/summarize endpoint
  const generateAiSummary = useCallback(async (paperId: string, textToSummarize: string) => {
    if (!textToSummarize || isSummarizing) return; // Do nothing if no text or already summarizing
    setIsSummarizing(true); // Indicate that summarization has started
    try {
      const response = await fetch('/api/summarize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ textToSummarize }), // Send the abstract text
      });
      if (!response.ok) {
         const errorData = await response.json().catch(() => ({})); // Try to parse error details
        throw new Error(`要約の生成に失敗しました。 Status: ${response.status}. ${errorData.error || ''}`);
      }
      const data = await response.json(); // Parse the summary response

      // Update the state of the specific paper to include the generated summary
      setPapers(prevPapers =>
        prevPapers.map(paper =>
          paper.id === paperId ? { ...paper, aiSummary: data.summary } : paper
        )
      );
    } catch (error) {
      console.error('Failed to generate summary:', error);
      // Optionally display an error message to the user (e.g., using a toast notification)
       alert(`要約生成エラー: ${error instanceof Error ? error.message : '不明なエラー'}`); // Simple alert for now
    } finally {
      setIsSummarizing(false); // Indicate that summarization has finished
    }
  }, [isSummarizing]); // Dependency: isSummarizing to prevent concurrent requests

  // Handler for the "Like" button
  const handleLike = () => {
    if (!currentPaper) return; // Do nothing if no paper is displayed

    console.log(`いいね: ${currentPaper.title} (ID: ${currentPaper.id})`); // Log for debugging (replace with actual logic)
    // likedPapers stateを更新
    setLikedPapers(prev => {
        // すでにいいねされていなければ追加
        if (!prev.includes(currentPaper.id)) {
            return [...prev, currentPaper.id];
        }
        return prev; // 既に含まれていれば変更しない
    });

    goToNextPaper(); // Move to the next paper
  };

  // Handler for the "Dislike" button
  const handleDislike = () => {
    if (!currentPaper) return; // Do nothing if no paper is displayed

    console.log(`興味なし: ${currentPaper.title} (ID: ${currentPaper.id})`); // Log for debugging (replace with actual logic)
    // Optionally record dislike information for recommendation logic

    goToNextPaper(); // Move to the next paper
  };

  // Function to advance to the next paper in the list
  const goToNextPaper = () => {
    const nextIndex = currentPaperIndex + 1;
    if (nextIndex < papers.length) {
      setCurrentPaperIndex(nextIndex); // Update the index
    } else {
      // Handle reaching the end of the paper list
      setMessage('表示できる論文は以上です。');
      // Optional: Keep the last paper displayed or show a different view
      // setCurrentPaperIndex(nextIndex); // Avoid going out of bounds if keeping last paper visible
    }
  };

  // --- Render Logic ---
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-br from-blue-50 via-white to-green-50 p-4 font-sans">
      {/* App Title */}
      <h1 className="text-3xl md:text-4xl font-bold mb-2 text-gray-800 tracking-tight">
        論文を見つけよう
      </h1>
      {/* ★★★ likedPapers を使用する部分 (いいね数を表示) ★★★ */}
      <p className="text-sm text-gray-500 mb-6">
        いいねした論文数: {likedPapers.length}
      </p>

      {/* Loading State */}
      {isLoading ? (
        <div className="text-center p-6 bg-white rounded-lg shadow-md w-full max-w-md">
          <p className="text-xl text-gray-700 mb-4">{message}</p>
          {/* Simple spinner animation */}
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500 mx-auto"></div>
        </div>
      ) : /* Message State (End of list, Error, No papers found) */
      message ? (
        <div className="text-center p-6 bg-white rounded-lg shadow-md w-full max-w-md">
          <p className="text-xl text-gray-700 mb-4">{message}</p>
          {/* Provide a button to reload papers */}
          <button
            onClick={fetchPapers}
            className="mt-4 bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-5 rounded-full transition-all duration-200 shadow-md focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 transform hover:scale-105"
          >
            再読み込み
          </button>
        </div>
      ) : /* Paper Card Display State */
      currentPaper ? (
        <div className="bg-white rounded-xl shadow-xl p-6 w-full max-w-2xl text-left transform transition-all duration-300 ease-in-out border border-gray-100">
          {/* Paper Title */}
          <h2 className="text-xl lg:text-2xl font-semibold mb-3 text-gray-900 leading-tight">
            {currentPaper.title}
          </h2>

          {/* Authors */}
          <p className="text-sm text-gray-500 mb-3 italic">
            Authors: {currentPaper.authors.join(', ')}
          </p>

          {/* Published/Updated Dates */}
          <div className="text-xs text-gray-400 mb-4 space-x-2">
            <span>Published: {new Date(currentPaper.published).toLocaleDateString()}</span>
            <span>/</span>
            <span>Updated: {new Date(currentPaper.updated).toLocaleDateString()}</span>
          </div>

          {/* AI Summary Section */}
          <div className="mb-5 p-4 bg-blue-50 rounded-lg border border-blue-200">
            <h3 className="font-semibold text-blue-800 mb-2 flex items-center justify-between">
              <span className="flex items-center">
                {/* Sparkle Icon */}
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1.5 text-blue-600" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M10 3a1 1 0 011 1v2.586l1.707-1.707a1 1 0 111.414 1.414L12.414 8H15a1 1 0 110 2h-2.586l1.707 1.707a1 1 0 11-1.414 1.414L11 10.414V13a1 1 0 11-2 0v-2.586l-1.707 1.707a1 1 0 11-1.414-1.414L7.586 9H5a1 1 0 110-2h2.586l-1.707-1.707a1 1 0 011.414-1.414L9 5.586V3a1 1 0 011-1z" clipRule="evenodd" />
                </svg>
                AIによる要約
              </span>
              {/* Generate Button - shown only if summary doesn't exist and not currently summarizing */}
              {!currentPaper.aiSummary && !isSummarizing && (
                <button
                  onClick={() => generateAiSummary(currentPaper.id, currentPaper.summary)}
                  className="bg-blue-500 hover:bg-blue-600 text-white text-xs font-bold py-1 px-3 rounded-full transition-all duration-200 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75 transform hover:scale-105"
                >
                  生成する
                </button>
              )}
            </h3>
            {/* Display summarizing message, generated summary, or placeholder */}
            {isSummarizing && currentPaper.id === papers[currentPaperIndex]?.id ? (
              <p className="text-sm text-blue-700 italic animate-pulse">要約を生成中...</p>
            ) : currentPaper.aiSummary ? (
              <p className="text-sm text-blue-900 leading-relaxed">{currentPaper.aiSummary}</p>
            ) : (
              <p className="text-sm text-gray-500 italic">（「生成する」ボタンを押してAI要約を表示）</p>
            )}
          </div>

          {/* Original Abstract (Collapsible) */}
          <details className="mb-5 group">
            <summary className="cursor-pointer text-sm font-medium text-gray-600 hover:text-gray-800 list-none flex items-center">
              <span className="group-open:rotate-90 transform transition-transform duration-200 mr-1">▶</span>
              元の要約 (Abstract) を表示
            </summary>
            <p className="text-gray-700 mt-2 text-sm bg-gray-50 p-4 rounded-md border border-gray-200 leading-relaxed">
              {currentPaper.summary}
            </p>
          </details>

          {/* Categories (Tags) */}
          <div className="flex flex-wrap gap-2 mb-6">
            {currentPaper.categories.map(category => (
              <span key={category} className="bg-gray-200 text-gray-800 text-xs font-medium px-3 py-1 rounded-full shadow-sm">
                {category}
              </span>
            ))}
          </div>

          {/* Action Buttons Area */}
          <div className="flex flex-col sm:flex-row justify-between items-center mt-8 pt-6 border-t border-gray-200">
             {/* PDF Link Button */}
             {currentPaper.pdfLink ? (
                <a
                  href={currentPaper.pdfLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center bg-gray-700 hover:bg-gray-800 text-white text-sm font-bold py-2 px-4 rounded-full transition-all duration-200 shadow-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-opacity-75 mb-4 sm:mb-0 transform hover:scale-105"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  PDFを開く
                </a>
             ) : (
                <div className="w-full sm:w-auto mb-4 sm:mb-0"></div> // Placeholder for alignment
             )}


            {/* Like/Dislike Buttons */}
            <div className="flex justify-center space-x-4">
              {/* Dislike Button */}
              <button
                onClick={handleDislike}
                className="bg-gradient-to-br from-red-400 to-pink-500 hover:from-red-500 hover:to-pink-600 text-white font-bold py-3 px-8 rounded-full transition-all transform hover:scale-105 duration-200 shadow-lg focus:outline-none focus:ring-2 focus:ring-red-400 focus:ring-opacity-75 flex items-center"
                aria-label="興味なし"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                興味なし
              </button>
              {/* Like Button */}
              <button
                onClick={handleLike}
                className="bg-gradient-to-br from-green-400 to-blue-500 hover:from-green-500 hover:to-blue-600 text-white font-bold py-3 px-8 rounded-full transition-all transform hover:scale-105 duration-200 shadow-lg focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75 flex items-center"
                aria-label="興味あり"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clipRule="evenodd" />
                </svg>
                興味あり
              </button>
            </div>
          </div>
        </div>
      ) : null /* Fallback for unexpected state (should not normally happen) */}

      {/* Optional Debug Area: Display liked paper IDs */}
      {/*
      <div className="mt-8 p-4 bg-gray-200 rounded w-full max-w-2xl text-xs">
        <h3 className="font-bold mb-2">いいねした論文ID:</h3>
        <pre>{JSON.stringify(likedPapers, null, 2)}</pre>
      </div>
      */}
    </div>
  );
}
